// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQyVKBvgppW9969U5YMKNz88Hrsz8vlQM',
    appId: '1:280130100983:web:2a9c4ef9cc25b02317bdf2',
    messagingSenderId: '280130100983',
    projectId: 'chatify-bb98b',
    authDomain: 'chatify-bb98b.firebaseapp.com',
    storageBucket: 'chatify-bb98b.appspot.com',
    measurementId: 'G-ZYRCJNN0Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNxK4OXtP4wPYpzmYvkZTV7kch8jkVXs',
    appId: '1:280130100983:android:ba535ebbb04228af17bdf2',
    messagingSenderId: '280130100983',
    projectId: 'chatify-bb98b',
    storageBucket: 'chatify-bb98b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1RX6EL3T9-7ixs4eXAsJg1m0G29ga0q4',
    appId: '1:280130100983:ios:1044bf3a6858f3fb17bdf2',
    messagingSenderId: '280130100983',
    projectId: 'chatify-bb98b',
    storageBucket: 'chatify-bb98b.appspot.com',
    iosBundleId: 'com.example.chatify',
  );
}
